/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaIndexRouteImport } from './routes/arena.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SuggestionsNewRouteImport } from './routes/suggestions.new'
import { Route as SuggestionsIdRouteImport } from './routes/suggestions.$id'
import { Route as MessagesUsernameRouteImport } from './routes/messages.$username'
import { Route as LessonsNewRouteImport } from './routes/lessons.new'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as ArenaStudioRouteImport } from './routes/arena.studio'
import { Route as ArenaSchoolsRouteImport } from './routes/arena.schools'
import { Route as ArenaProfileRouteImport } from './routes/arena.profile'
import { Route as ArenaLeaderboardRouteImport } from './routes/arena.leaderboard'
import { Route as ArenaDailyRouteImport } from './routes/arena.daily'
import { Route as ArenaChallengesRouteImport } from './routes/arena.challenges'
import { Route as ArenaBattlesRouteImport } from './routes/arena.battles'
import { Route as LessonsLessonIdEditRouteImport } from './routes/lessons.$lessonId.edit'
import { Route as LessonsLessonIdDiffRouteImport } from './routes/lessons.$lessonId.diff'
import { Route as ArenaChallengesSlugRouteImport } from './routes/arena.challenges.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArenaRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsNewRoute = SuggestionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SuggestionsRoute,
} as any)
const SuggestionsIdRoute = SuggestionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuggestionsRoute,
} as any)
const MessagesUsernameRoute = MessagesUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MessagesRoute,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaStudioRoute = ArenaStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaSchoolsRoute = ArenaSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaProfileRoute = ArenaProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaLeaderboardRoute = ArenaLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaDailyRoute = ArenaDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaChallengesRoute = ArenaChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaBattlesRoute = ArenaBattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => ArenaRoute,
} as any)
const LessonsLessonIdEditRoute = LessonsLessonIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LessonsLessonIdRoute,
} as any)
const LessonsLessonIdDiffRoute = LessonsLessonIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => LessonsLessonIdRoute,
} as any)
const ArenaChallengesSlugRoute = ArenaChallengesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArenaChallengesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/arena/battles': typeof ArenaBattlesRoute
  '/arena/challenges': typeof ArenaChallengesRouteWithChildren
  '/arena/daily': typeof ArenaDailyRoute
  '/arena/leaderboard': typeof ArenaLeaderboardRoute
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/schools': typeof ArenaSchoolsRoute
  '/arena/studio': typeof ArenaStudioRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/suggestions/$id': typeof SuggestionsIdRoute
  '/suggestions/new': typeof SuggestionsNewRoute
  '/u/$username': typeof UUsernameRoute
  '/arena/': typeof ArenaIndexRoute
  '/arena/challenges/$slug': typeof ArenaChallengesSlugRoute
  '/lessons/$lessonId/diff': typeof LessonsLessonIdDiffRoute
  '/lessons/$lessonId/edit': typeof LessonsLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/arena/battles': typeof ArenaBattlesRoute
  '/arena/challenges': typeof ArenaChallengesRouteWithChildren
  '/arena/daily': typeof ArenaDailyRoute
  '/arena/leaderboard': typeof ArenaLeaderboardRoute
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/schools': typeof ArenaSchoolsRoute
  '/arena/studio': typeof ArenaStudioRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/suggestions/$id': typeof SuggestionsIdRoute
  '/suggestions/new': typeof SuggestionsNewRoute
  '/u/$username': typeof UUsernameRoute
  '/arena': typeof ArenaIndexRoute
  '/arena/challenges/$slug': typeof ArenaChallengesSlugRoute
  '/lessons/$lessonId/diff': typeof LessonsLessonIdDiffRoute
  '/lessons/$lessonId/edit': typeof LessonsLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/arena/battles': typeof ArenaBattlesRoute
  '/arena/challenges': typeof ArenaChallengesRouteWithChildren
  '/arena/daily': typeof ArenaDailyRoute
  '/arena/leaderboard': typeof ArenaLeaderboardRoute
  '/arena/profile': typeof ArenaProfileRoute
  '/arena/schools': typeof ArenaSchoolsRoute
  '/arena/studio': typeof ArenaStudioRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/suggestions/$id': typeof SuggestionsIdRoute
  '/suggestions/new': typeof SuggestionsNewRoute
  '/u/$username': typeof UUsernameRoute
  '/arena/': typeof ArenaIndexRoute
  '/arena/challenges/$slug': typeof ArenaChallengesSlugRoute
  '/lessons/$lessonId/diff': typeof LessonsLessonIdDiffRoute
  '/lessons/$lessonId/edit': typeof LessonsLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/leaderboard'
    | '/legal'
    | '/messages'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/schools'
    | '/settings'
    | '/suggestions'
    | '/terms'
    | '/arena/battles'
    | '/arena/challenges'
    | '/arena/daily'
    | '/arena/leaderboard'
    | '/arena/profile'
    | '/arena/schools'
    | '/arena/studio'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/messages/$username'
    | '/suggestions/$id'
    | '/suggestions/new'
    | '/u/$username'
    | '/arena/'
    | '/arena/challenges/$slug'
    | '/lessons/$lessonId/diff'
    | '/lessons/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/leaderboard'
    | '/legal'
    | '/messages'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/schools'
    | '/settings'
    | '/suggestions'
    | '/terms'
    | '/arena/battles'
    | '/arena/challenges'
    | '/arena/daily'
    | '/arena/leaderboard'
    | '/arena/profile'
    | '/arena/schools'
    | '/arena/studio'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/messages/$username'
    | '/suggestions/$id'
    | '/suggestions/new'
    | '/u/$username'
    | '/arena'
    | '/arena/challenges/$slug'
    | '/lessons/$lessonId/diff'
    | '/lessons/$lessonId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/leaderboard'
    | '/legal'
    | '/messages'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/schools'
    | '/settings'
    | '/suggestions'
    | '/terms'
    | '/arena/battles'
    | '/arena/challenges'
    | '/arena/daily'
    | '/arena/leaderboard'
    | '/arena/profile'
    | '/arena/schools'
    | '/arena/studio'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/messages/$username'
    | '/suggestions/$id'
    | '/suggestions/new'
    | '/u/$username'
    | '/arena/'
    | '/arena/challenges/$slug'
    | '/lessons/$lessonId/diff'
    | '/lessons/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArenaRoute: typeof ArenaRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  FeedbackRoute: typeof FeedbackRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LegalRoute: typeof LegalRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchoolsRoute: typeof SchoolsRoute
  SettingsRoute: typeof SettingsRoute
  SuggestionsRoute: typeof SuggestionsRouteWithChildren
  TermsRoute: typeof TermsRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRouteWithChildren
  LessonsNewRoute: typeof LessonsNewRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/': {
      id: '/arena/'
      path: '/'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions/new': {
      id: '/suggestions/new'
      path: '/new'
      fullPath: '/suggestions/new'
      preLoaderRoute: typeof SuggestionsNewRouteImport
      parentRoute: typeof SuggestionsRoute
    }
    '/suggestions/$id': {
      id: '/suggestions/$id'
      path: '/$id'
      fullPath: '/suggestions/$id'
      preLoaderRoute: typeof SuggestionsIdRouteImport
      parentRoute: typeof SuggestionsRoute
    }
    '/messages/$username': {
      id: '/messages/$username'
      path: '/$username'
      fullPath: '/messages/$username'
      preLoaderRoute: typeof MessagesUsernameRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/studio': {
      id: '/arena/studio'
      path: '/studio'
      fullPath: '/arena/studio'
      preLoaderRoute: typeof ArenaStudioRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/schools': {
      id: '/arena/schools'
      path: '/schools'
      fullPath: '/arena/schools'
      preLoaderRoute: typeof ArenaSchoolsRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/profile': {
      id: '/arena/profile'
      path: '/profile'
      fullPath: '/arena/profile'
      preLoaderRoute: typeof ArenaProfileRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/leaderboard': {
      id: '/arena/leaderboard'
      path: '/leaderboard'
      fullPath: '/arena/leaderboard'
      preLoaderRoute: typeof ArenaLeaderboardRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/daily': {
      id: '/arena/daily'
      path: '/daily'
      fullPath: '/arena/daily'
      preLoaderRoute: typeof ArenaDailyRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/challenges': {
      id: '/arena/challenges'
      path: '/challenges'
      fullPath: '/arena/challenges'
      preLoaderRoute: typeof ArenaChallengesRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/battles': {
      id: '/arena/battles'
      path: '/battles'
      fullPath: '/arena/battles'
      preLoaderRoute: typeof ArenaBattlesRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/lessons/$lessonId/edit': {
      id: '/lessons/$lessonId/edit'
      path: '/edit'
      fullPath: '/lessons/$lessonId/edit'
      preLoaderRoute: typeof LessonsLessonIdEditRouteImport
      parentRoute: typeof LessonsLessonIdRoute
    }
    '/lessons/$lessonId/diff': {
      id: '/lessons/$lessonId/diff'
      path: '/diff'
      fullPath: '/lessons/$lessonId/diff'
      preLoaderRoute: typeof LessonsLessonIdDiffRouteImport
      parentRoute: typeof LessonsLessonIdRoute
    }
    '/arena/challenges/$slug': {
      id: '/arena/challenges/$slug'
      path: '/$slug'
      fullPath: '/arena/challenges/$slug'
      preLoaderRoute: typeof ArenaChallengesSlugRouteImport
      parentRoute: typeof ArenaChallengesRoute
    }
  }
}

interface ArenaChallengesRouteChildren {
  ArenaChallengesSlugRoute: typeof ArenaChallengesSlugRoute
}

const ArenaChallengesRouteChildren: ArenaChallengesRouteChildren = {
  ArenaChallengesSlugRoute: ArenaChallengesSlugRoute,
}

const ArenaChallengesRouteWithChildren = ArenaChallengesRoute._addFileChildren(
  ArenaChallengesRouteChildren,
)

interface ArenaRouteChildren {
  ArenaBattlesRoute: typeof ArenaBattlesRoute
  ArenaChallengesRoute: typeof ArenaChallengesRouteWithChildren
  ArenaDailyRoute: typeof ArenaDailyRoute
  ArenaLeaderboardRoute: typeof ArenaLeaderboardRoute
  ArenaProfileRoute: typeof ArenaProfileRoute
  ArenaSchoolsRoute: typeof ArenaSchoolsRoute
  ArenaStudioRoute: typeof ArenaStudioRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
}

const ArenaRouteChildren: ArenaRouteChildren = {
  ArenaBattlesRoute: ArenaBattlesRoute,
  ArenaChallengesRoute: ArenaChallengesRouteWithChildren,
  ArenaDailyRoute: ArenaDailyRoute,
  ArenaLeaderboardRoute: ArenaLeaderboardRoute,
  ArenaProfileRoute: ArenaProfileRoute,
  ArenaSchoolsRoute: ArenaSchoolsRoute,
  ArenaStudioRoute: ArenaStudioRoute,
  ArenaIndexRoute: ArenaIndexRoute,
}

const ArenaRouteWithChildren = ArenaRoute._addFileChildren(ArenaRouteChildren)

interface MessagesRouteChildren {
  MessagesUsernameRoute: typeof MessagesUsernameRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesUsernameRoute: MessagesUsernameRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface SuggestionsRouteChildren {
  SuggestionsIdRoute: typeof SuggestionsIdRoute
  SuggestionsNewRoute: typeof SuggestionsNewRoute
}

const SuggestionsRouteChildren: SuggestionsRouteChildren = {
  SuggestionsIdRoute: SuggestionsIdRoute,
  SuggestionsNewRoute: SuggestionsNewRoute,
}

const SuggestionsRouteWithChildren = SuggestionsRoute._addFileChildren(
  SuggestionsRouteChildren,
)

interface LessonsLessonIdRouteChildren {
  LessonsLessonIdDiffRoute: typeof LessonsLessonIdDiffRoute
  LessonsLessonIdEditRoute: typeof LessonsLessonIdEditRoute
}

const LessonsLessonIdRouteChildren: LessonsLessonIdRouteChildren = {
  LessonsLessonIdDiffRoute: LessonsLessonIdDiffRoute,
  LessonsLessonIdEditRoute: LessonsLessonIdEditRoute,
}

const LessonsLessonIdRouteWithChildren = LessonsLessonIdRoute._addFileChildren(
  LessonsLessonIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArenaRoute: ArenaRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  FeedbackRoute: FeedbackRoute,
  LeaderboardRoute: LeaderboardRoute,
  LegalRoute: LegalRoute,
  MessagesRoute: MessagesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchoolsRoute: SchoolsRoute,
  SettingsRoute: SettingsRoute,
  SuggestionsRoute: SuggestionsRouteWithChildren,
  TermsRoute: TermsRoute,
  LessonsLessonIdRoute: LessonsLessonIdRouteWithChildren,
  LessonsNewRoute: LessonsNewRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
