/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as MessagesUsernameRouteImport } from './routes/messages.$username'
import { Route as LessonsNewRouteImport } from './routes/lessons.new'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as LessonsLessonIdEditRouteImport } from './routes/lessons.$lessonId.edit'
import { Route as LessonsLessonIdDiffRouteImport } from './routes/lessons.$lessonId.diff'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUsernameRoute = MessagesUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MessagesRoute,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdEditRoute = LessonsLessonIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LessonsLessonIdRoute,
} as any)
const LessonsLessonIdDiffRoute = LessonsLessonIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => LessonsLessonIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/lessons/$lessonId/diff': typeof LessonsLessonIdDiffRoute
  '/lessons/$lessonId/edit': typeof LessonsLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/lessons/$lessonId/diff': typeof LessonsLessonIdDiffRoute
  '/lessons/$lessonId/edit': typeof LessonsLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/lessons/$lessonId/diff': typeof LessonsLessonIdDiffRoute
  '/lessons/$lessonId/edit': typeof LessonsLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/leaderboard'
    | '/legal'
    | '/messages'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/messages/$username'
    | '/u/$username'
    | '/lessons/$lessonId/diff'
    | '/lessons/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/leaderboard'
    | '/legal'
    | '/messages'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/messages/$username'
    | '/u/$username'
    | '/lessons/$lessonId/diff'
    | '/lessons/$lessonId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/explore'
    | '/feed'
    | '/feedback'
    | '/leaderboard'
    | '/legal'
    | '/messages'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/messages/$username'
    | '/u/$username'
    | '/lessons/$lessonId/diff'
    | '/lessons/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  FeedbackRoute: typeof FeedbackRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LegalRoute: typeof LegalRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRouteWithChildren
  LessonsNewRoute: typeof LessonsNewRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$username': {
      id: '/messages/$username'
      path: '/$username'
      fullPath: '/messages/$username'
      preLoaderRoute: typeof MessagesUsernameRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId/edit': {
      id: '/lessons/$lessonId/edit'
      path: '/edit'
      fullPath: '/lessons/$lessonId/edit'
      preLoaderRoute: typeof LessonsLessonIdEditRouteImport
      parentRoute: typeof LessonsLessonIdRoute
    }
    '/lessons/$lessonId/diff': {
      id: '/lessons/$lessonId/diff'
      path: '/diff'
      fullPath: '/lessons/$lessonId/diff'
      preLoaderRoute: typeof LessonsLessonIdDiffRouteImport
      parentRoute: typeof LessonsLessonIdRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesUsernameRoute: typeof MessagesUsernameRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesUsernameRoute: MessagesUsernameRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface LessonsLessonIdRouteChildren {
  LessonsLessonIdDiffRoute: typeof LessonsLessonIdDiffRoute
  LessonsLessonIdEditRoute: typeof LessonsLessonIdEditRoute
}

const LessonsLessonIdRouteChildren: LessonsLessonIdRouteChildren = {
  LessonsLessonIdDiffRoute: LessonsLessonIdDiffRoute,
  LessonsLessonIdEditRoute: LessonsLessonIdEditRoute,
}

const LessonsLessonIdRouteWithChildren = LessonsLessonIdRoute._addFileChildren(
  LessonsLessonIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  FeedbackRoute: FeedbackRoute,
  LeaderboardRoute: LeaderboardRoute,
  LegalRoute: LegalRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  LessonsLessonIdRoute: LessonsLessonIdRouteWithChildren,
  LessonsNewRoute: LessonsNewRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
